### ISSUE TITLE
Link to Chatroom

### ISSUE THREAD

**Issue by theaverageguy** [UnitexGramLab/gramlab-ide#1]
Hello @martinec .
I have applied as a student intern for GSoC under Unitex/Gramlab.
I am developing small prototypes for the projects I have applied for to show my skills. I am requesting for a link to a chatroom where I can communicate with the mentors easily about my interest for Gramlab and for developing myself initially to be a good candidate to work under Unitex/Gramlab.

Thanks.

**Comment by martinec** [comment]
Hello @theaverageguy 

Thank you for your interest in contributing with Unitex/GramLab development. GSoC students application deadline finished on 25 March 19:00 UTC.  Feel free to fork this repository and send a pull-request to its develop branch if you want to fix a bug, submit a new feature,  or anything else. For any other request, please start a new thread on the [Users' Forum](http://forum.unitexgramlab.org).

Thanks.

**Comment by theaverageguy** [comment]
@martinec I did apply on time. :)
Thank you for sharing the link to the forum. I am looking forward to contributing to Unitex/Gramlab for this GSoC. 
Thanks.
