### ISSUE TITLE
Fst2List option is unclear

### ISSUE THREAD

**Issue by Kalkhas** [UnitexGramLab/gramlab-ide#103]
Fst2List recursive exploration option description makes the behaviour of each choice unclear.
* "_Only paths_" doesn't imply clearly the recursive exploration.
* "_Do not explore subgraphs recursively_" doesn't explain what is the expected output.

![issue-100](https://user-images.githubusercontent.com/12595039/39919158-1211ea86-5513-11e8-8a27-c6a0cf630e51.png)

**Comment by martinec** [comment]
The better would be to prepend a label "Calls to subgraphs:" before the the two option buttons, something like this:

`Calls to subgraphs: (o) Explore calls recursively () Print calls without exploring it`

This is consistent with the stated in the User Manual, section 6.5, Exploring grammar paths.
