### ISSUE TITLE
Enhance explore graph paths UI

### ISSUE THREAD

**Issue by martinec** [UnitexGramLab/gramlab-ide#122]
The current UI for explore graph paths seems kind of messy because there's so much floating stuff:

<p align="center">
<img src="https://user-images.githubusercontent.com/800627/45828464-dd915280-bcf8-11e8-9f7d-f65567402240.png" data-canonical-src="https://user-images.githubusercontent.com/800627/45828464-dd915280-bcf8-11e8-9f7d-f65567402240.png" width="336" height="246" />
</p>

To put a little bit of order would be the best :

<p align="center">
<img src="https://user-images.githubusercontent.com/800627/45829683-c7d15c80-bcfb-11e8-874e-abd742e864fe.png" data-canonical-src="https://user-images.githubusercontent.com/800627/45829683-c7d15c80-bcfb-11e8-874e-abd742e864fe.png" width="340" height="280" />
</p>

**Comment by Kalkhas** [comment]
What would you want the 'Help' button to display ?

**Comment by martinec** [comment]
> What would you want the 'Help' button to display ?

An URL, for now (not yet available) http://learn.unitexgramlab.org/user-manual/chapter-07/section-05
