### ISSUE TITLE
The GPL, MIT license and LGPLLR are distribution licenses that don't need acceptance

### ISSUE THREAD

**Issue by bertvandepoel** [UnitexGramLab/gramlab-ide#161]
Currently, the GramLab installer incorrectly creates the perception that the licenses of its components need to be accepted to be able to use the application. However, the GPL, MIT License and LGPLLR are all distribution licenses. They do not govern how an application can be used but only the rules that apply when someone wishes to distribute a copy or derived work. 

Recently, many projects have resolved this problem by removing any form of necessary acceptance during installation or use.

I refer to the official GPL FAQ for more details https://www.gnu.org/licenses/gpl-faq.en.html#ClickThrough as well as several books on the subject including https://flylib.com/books/en/4.467.1.75/1/ and [Open Source Licensing: Software Freedom and Intellectual Property Law by Lawrence Rosen](https://learning.oreilly.com/library/view/open-source-licensing/0131487876/) (sadly the full text of the latter is no longer available, it seems). This further supports the point that the GPL and licenses similar to it (including the MIT License) are distribution licenses that rely on copyright and not contract law, and therefore don't require acceptance.

**Comment by martinec** [comment]
I have no problem to disable the license acceptance stage. That said, I am seeking @eric-laporte's thoughts on the matter.

Lastly, note that the related repository, i.e. the Unitex/GramLab installer, is rather available here https://github.com/UnitexGramLab/unitex-packaging-windows. 

I am closing this issue for now so it can be opened in the right place.

**Comment by bertvandepoel** [comment]
@martinec I wasn't too sure where to file this. I noticed it in the Linux installer, but presumed it would be in the others too (as you've just illustrated). Do I file two issues, both for https://github.com/UnitexGramLab/unitex-packaging-unix and https://github.com/UnitexGramLab/unitex-packaging-windows or what is the preferred option?
