### ISSUE TITLE
Instructions for testing don't tell where to copy the language directories

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/gramlab-ide#166]
Previously, several developers compiling, installing and testing Unitex for the first time have faced problems when they launched it for the first time. Unitex should propose to select a language from a list, but there is a condition that must be met for Unitex to find a list of languages. The instructions for testing don't give this condition, it could be: 'make sure that at least one language directory cloned from unitex-lingua is located in `/path/to/unitexgramlab-release/`'.

**What steps will reproduce the problem?**

  1. Compile and install Unitex without downloading data from unitex-lingua.
  2. Launch Unitex.

**What is the expected output?**

Unitex should propose to select a language from a list.

**What do you see instead?**

The list of languages is empty.

**More info**

- Unitex/GramLab IDE version: 21 June 2022
- UnitexToolLogger version: 21 June 2022 
- Did this work before?: [ ] yes [x] no

**Comment by martinec** [comment]
Effectively, when Unitex/GramLab is installed without going through the installers, the issue you mention arises.

For developers, I suggest to put a mention in the contribution guidelines, as well as in the readme.

On the other hand, there is no reason to clone unitex-lingua, as this is not a suitable approach. Instead, users can download one of the available languages directly from https://unitexgramlab.org/releases/latest-stable/lingua/

Ideally, The IDE requires a notion of a language folder. This will avoid displaying folders that do not contain a language.

The approach I propose is as follows:

Each language folder contains a file, named `<language_code>.info`, e.g. `fr.info` with the following mandatory information:

```
language_name = French
language_native = Français
langue_code = fr
```

(check out the Languages table on https://github.com/UnitexGramLab/unitex-lingua)

Then, the IDE must proposes as languages only folders containing a `.info` file with at least the 3 information mentioned (language_name, language_native, language_code)

If no language file is found, the IDE may propose to search in another location, and shall mention that other languages are avalaible to download from https://unitexgramlab.org/releases/latest-stable/lingua/

**Comment by eric-laporte** [comment]
PR #167 gives instructions for developers that install and test Unitex now. Your suggestion to implement a notion of language folder in the IDE will require another PR.
