### ISSUE TITLE
Pressing [Esc] closes the current dialog box 

### ISSUE THREAD

**Issue by martinec** [UnitexGramLab/gramlab-ide#18]
Submitted by Denis Maurel.

Add an <key>Esc</key> hotkey to close the current dialog box

**Comment by Mukarr** [comment]
@martinec 
Do file editor and graph editor also need this feature to close on pressing Esc?

**Comment by martinec** [comment]
For now let's say yes.

**Comment by Mukarr** [comment]
Or may be we can minimize them on Esc ?
