### ISSUE TITLE
Find and replace for graphs

### ISSUE THREAD

**Issue by phmz** [UnitexGramLab/gramlab-ide#24]
Currently, there is no way to find and replace the content of one or more boxes at the same time.
I already have implemented this feature please see my pull request #23.
The feature can be used by either clicking on the magnifying glass in the graph toolbar or in the FSGraph menu.
To avoid any issue, you cannot replace the content of empty boxes (containing only \<E>) and standalone boxes.

**Comment by alexis-neme** [comment]
Bug:
Test: Open NC-*.grf  from  French>inflection folder many  

**Find what:** <$2>
**Graphs :** All open graphs
_Status bar: Found 14 boxes matches with <$2>_ 

Button "Find Next" does not display the next graph with the box in green as expected.
