### ISSUE TITLE
Find and replace a sequence of boxes

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/gramlab-ide#26]
**1. Dialog box**

Add 2 tabs to the current "Find and replace" dialog box:
- "Inside one box" (with the present "Find and replace" dialog box)
- "Complete boxes"

The "Complete boxes" tab should look like the other but with several differences:

1.1. The "Find what" query
"Find what" and 3 lines:
- a radio button for a choice between "One box after another" and "All boxes at once".
- a line of instructions. The radio button switches the instructions between: "Select first box, then click "Add", etc." and "Select a sequence of connected boxes in a graph and click "Add"".
- an editable text field, and an "Add" button on the right.

In the text field, the content of each box is displayed with a delimiter between them. The delimiter is a non-ASCII character unlikely to belong to the alphabet of a language (a triangle pointing to the right? or ◊).

Examples of "Find what" queries: 
- freedom◊of◊the◊press
- freedom of the press
- 고/{고,고.EV+TE+INT}◊<E>◊요/{요,요.EV+TE+AUH}
- 고요/{고요,고요.EV+TE+INT+AUH}

1.2. The "Replace with" pattern
Exactly the same elements repeated.

Examples of "Replace with" patterns: 
- freedom of the press
- freedom◊of◊the◊press
- 고요/{고요,고요.EV+TE+INT+AUH}
- 고/{고,고.EV+TE+INT}◊<E>◊요/{요,요.EV+TE+AUH}

1.3. "Find what" options
"Case sensitive" : checked by default.
No "Match only a whole line" option (meaningless).
In a future version, "Use regular expressions" for the research might be useful. In that case, \1 \2 \3 etc. should be available in the substitution query.

1.4. Other buttons: like in the present "find and replace" box.

**2. Functionality**

2.1. The number of occurrences found is displayed in the status bar field.

2.2. "Find  next" and "Find previous" find and select an occurrence of the  "find what" query.
If a transition enters into a box which is not the first, and if a transition goes out of a box which is not the last:
- select the occurrence,
- issue a warning "Part of this occurrence is shared with another path" in the status text field
- disable and gray the "Replace" button (this is the only case when it is grayed).

2.3. "Replace" and "Replace all" replace the occurrences of the "find what" query by the "replace with" pattern, except if they have an ingoing transition  into a box which is not the first, or an outgoing transition from a box which is not the last.

**Comment by martinec** [comment]
Resolved with 3d3325bc3bef5719ef9b7a03601ed94cffafa5ee
