### ISSUE TITLE
Save Snt As

### ISSUE THREAD

**Issue by phmz** [UnitexGramLab/gramlab-ide#38]
It would be useful to be able to save the current Snt and its folder.

**What is the expected output?**
Save the current .snt file and the corresponding _snt directory with its contents. It should be allowed to save them in another directory than Corpus. Give all files the date of the copy. The new snt is set as the current corpus.

**Comment by Mukarr** [comment]
Approved.
**Suggestion:** In order to improve user experience, we can add a shortcut for `Save As...`, probably `Ctrl+S` . What do you think?
