### ISSUE TITLE
Lookup not operational on user dictionaries

### ISSUE THREAD

**Issue by martinec** [UnitexGramLab/gramlab-ide#4]
Submitted by @eric-laporte 

The lookup functionality (Unitex menu DELA > Lookup...) is operational on system dictionaries, but not on user's dictionaries.

**What steps will reproduce the problem?**

Copy the same dictionary inside the system Unitex directory and inside the user's Unitex dictionary

**What is the expected output?**

The entries found in the system dictionary are also available in the user's dictionary.

**What do you see instead?**

The entries found in the system dictionary are not found in the user's dictionary.

**Comment by theaverageguy** [comment]
Helping with this too @martinec .

**Comment by nikhilgupta23** [comment]
I'm unable to reproduce this error. It is working as expected @martinec .

**Comment by eric-laporte** [comment]
Dear all,

I made a new test with stable version 3.1 on Windows XP and now it works 
as expected. Good news.
Thanks,

Eric Laporte

Le 04/04/2016 08:54, Nikhil Gupta a écrit :
>
> I'm unable to reproduce this error. It is working as expected 
> @martinec <https://github.com/martinec> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/UnitexGramLab/gramlab-ide/issues/4#issuecomment-205161500>
>

-- 

*ÉRIC LAPORTE*
Professeur
*LIGM*

*T* : +33 1 60 95 75 52
BÂTIMENT COPERNIC - BUREAU 4B090
eric.laporte@univ-paris-est.fr
http://igm.univ-mlv.fr/~laporte/index_en.html 
<http://igm.univ-mlv.fr/%7Elaporte/index_en.html>

*UPEM - Université Paris-Est Marne-la-Vallée*
CITÉ DESCARTES - 5 BOULEVARD DESCARTES - CHAMPS-SUR-MARNE
77454 MARNE-LA-VALLÉE CEDEX 2 - WWW.U-PEM.FR <http://www.u-pem.fr>

**Comment by martinec** [comment]
Thank you @theaverageguy, @nikhilgupta23, @eric-laporte for the feedback. I will close this issue now since it is done.
