### ISSUE TITLE
Specialized "Open..." options for specific file types in "File Edition" menu

### ISSUE THREAD

**Issue by martinec** [UnitexGramLab/gramlab-ide#5]
Submitted by @vasiljevic

Different file types (like .TXT, .DIC, etc) may have different default folder and default extension. Specialized "Open..." options in "File Edition" menu will offer appropriate default folder and default file
extension in file open dialog. This small change may be useful for some users, as Denis Maurel noted in his post: https://groups.google.com/forum/#!searchin/unitex-gramlab/edition/unitex-gramlab/iRTR75xD21Q/16Mvt8SHGkEJ

**Comment by nikhilgupta23** [comment]
I am working on this.

**Comment by nikhilgupta23** [comment]
@martinec Can you please provide a list of all the extensions that need can be included in the Specialized File Edition Open menu. I want to compare it with the parts that I've coded.

**Comment by martinec** [comment]
Your help is greatly appreciated.  AFAIK, for the `File Edition > Open` menu, the plain-text (user-editable) files that will be useful to open are:

- `*.txt` : Text files. Users Manual 14.2, 14.4
- `*.csc` : Cascade configuration files. Users Manual 12.1.1
- `*.dic` : Dictionaries. Users Manual 3.3, 14.7

If `Lang` is a Unitex language folder, then the related directories are :

- `Lang/` : '*.txt'
- `Lang/CasSys` : '*.csc'
- `Lang/Corpus` : '*.txt'
- `Lang/Dela` : '*.dic'

For now, I will mark this issue as `needs:feedback` to wait for more comments and build consensus.
