### ISSUE TITLE
Suggestion to solve the ambiguous corpus problem in Unitex

### ISSUE THREAD

**Issue by mufeedalali** [UnitexGramLab/gramlab-ide#57]
In a corpus with multi-candidate tagging, each sentence has several solutions, but we don't have within Unitex/GramLab rules that always allow to find the best solution, so here is a suggestion to solve this problem : using the Unitex text automaton and Gate machine learning to score the candidates and choose the best score among them.
Gate machine learning consists of two basic operations: first, doing the training on a unambiguously tagged corpus to generate a trained model, and second, applying the model on the multi-candidate corpus.

**Comment by martinec** [comment]
I'm closing this issue. the [Unitex/GramLab forum](http://forum.unitexgramlab.org) is probably a better place to discuss this suggestion.
