### ISSUE TITLE
Colour marking in the text automaton

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/gramlab-ide#59]
Some visual marking of unambiguously tagged parts and of untagged parts in the text automaton might be useful to users of the text automaton, especially to linguists that revise the tagging, a very repetitive task. The HUFS University in Korea is testing various forms of colour marking. Here are their best choices. The best colour marking might be extended to all languages, if users and developers agree.
1) Boxes for untagged tokens: lavender blue (CCCCFF) background inside.
2) Boxes for unambiguously tagged items: periwinkle blue (9999FF) or light green (CCEB94) background inside; lines as thick as normal boxes; no bold characters.
3) Entirely unambiguously tagged sentences: periwinkle blue (9999FF) or cornflower blue (99C9E4) background in boxes (maybe except for untagged tokens); transitions either periwinkle blue (9999FF) or the same colour as other sentences, not yellow.

**Comment by alexis-neme** [comment]
Hi all,

Colors should be intuitive, as much as we can. The traffic lights
(Green-yellow-red) is the most intuitive coloration, as far as I know.
here, some suggestions:


   - *Blue *(like a freeway, all good in a sentence, for a blue sky, no
   cloud): used for all boxes in a sentence  tagged no ambiguous tagg
   included in the whole sentence. (we can increment the sentence counter
   without looking in tagging details)
   - *Green *: for a box with an unambiguous tag in a sentence with
   ambiguous tags.
   - *Yellow*: future use, or for a box with slight ambiguity (to be
   defined) such as inflexional ambiguity based on "implode" program.
   - *Red*: for a box with no tag.

Hope these suggestions will help!

Cheers,

*Bests*

*----------*

*Alexis Neme*

Computer Scientist - Arabic NLP
FR-PT-EN-AR (DE, Tagalog)

http://tasrif.univ-mlv.fr/About.html




UPEM - LIGM - Laboratoire d'Informatique Gaspard-Monge
Bureau 4B045, 5 Bd Descartes, Champs-sur-Marne
77454 Marne-la-Vallée Cedex 2, France

Tél : 00 33 1 60 95 77 17

**Comment by eric-laporte** [comment]
HUFS' best choice after new tests is as follows:

    Boxes for untagged tokens: lavender blue (CCCCFF) background inside.
    Boxes for unambiguously tagged items: light green (CCEB94) background inside; lines as thick as normal boxes; no bold characters.
    Entirely unambiguously tagged sentences: cornflower blue (99C9E4) background in boxes (except for untagged tokens); box frames are cornflower blue; transitions and empty boxes are black, not yellow.
![cornflower_linear_black_trans](https://cloud.githubusercontent.com/assets/11441317/21714802/35aeec62-d401-11e6-931d-9c603032c1c3.png)
![green](https://cloud.githubusercontent.com/assets/11441317/21714803/35b6509c-d401-11e6-9f84-fdfb2c0b130f.PNG)

**Comment by eric-laporte** [comment]
HUFS' best choice after new tests is as follows:
- Boxes for untagged tokens: lavender blue (CCCCFF) background inside.
- Boxes for unambiguously tagged items: light green (CCEB94) background inside; lines as thick as normal boxes; no bold characters inside.

![green](https://cloud.githubusercontent.com/assets/11441317/21714803/35b6509c-d401-11e6-9f84-fdfb2c0b130f.PNG)

- Entirely unambiguously tagged sentences: cornflower blue (99C9E4) background in boxes (except for untagged tokens); box frames are cornflower blue; transitions and empty boxes are black, not yellow.

![cornflower_linear_black_trans](https://cloud.githubusercontent.com/assets/11441317/21714802/35aeec62-d401-11e6-931d-9c603032c1c3.png)

**Comment by mdamis** [comment]
Colors in the text automaton now match the latest choice from the HUFS.
Note that these changes only apply to Korean texts.

See commit https://github.com/UnitexGramLab/gramlab-ide/commit/d9396aa2565f4185cb08e91bf3d403d1f0f8a656 for more details.
