### ISSUE TITLE
Let user set name of output file containing list of paths of graph

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/gramlab-ide#61]
In the present 'FSGraph > Tools > Explore graph paths' function, the output (which is the list of the paths of a graph) is automatically saved in list.txt in the directory of the language.
The user should be allowed to choose and set the name and directory of the output file.

**Comment by rewopkram** [comment]
Hello Eric if the "Do not explore subgraphs recursively" is selected the file is saved in <graphname>autolst.txt in the same directory as the graph. Would you like this behaviour changed also to allow the user to set the name and directory of the file?

**Comment by eric-laporte** [comment]
Hi Rewopkram, yes, users whould be able to set the name and directory of the file no matter the options.
