### ISSUE TITLE
Output of Fst2List not displayed

### ISSUE THREAD

**Issue by martinec** [UnitexGramLab/gramlab-ide#7]
Submitted by @eric-laporte 

The results of Fst2List (list the paths of a graph, with a limit on the number of paths, cf. manual section 6.5) are correctly saved in a file list.txt, but not displayed in the dialog box when Fst2List issues warnings such as 'the graph 12 recognizes <E>'.

**What steps will reproduce the problem?**

In the experiment recorded in the attached log, I launch Fst2List through the Unitex menu item 'FSGraph > Tools > Explore graph paths' with the default parameters.

**What is the expected output?**

The 'Explore graph paths' dialog box notifies that the results have been saved and display the results.

**What do you see instead?**

The 'Working...' window issues warnings. The 'Explore graph paths' dialog box does not notify that the results have been saved and does not display the results. The results are correctly saved in a file list.txt. 

The 'Explore graph paths' dialog box is on the foreground and no other Unitex window can come to the foreground, so I close the dialog box. Then I launch Fst2List again in the same way. This time, the title of the dialog box is '100 lines' and it displays the results of the preceding request.

**More info**

This behaviour was already present in Unitex3.0, but it is confusing for the user and it complicates the task of analysing what works and what does not work in Fst2List.

Quoting Sebastien Paumier today about this problem: "la solution stable serait d'ajouter un paramètre booléen pour indiquer que l'object ToDo passé à Launcher.exec() doit être exécuté sans attendre que la fenêtre d'exécution des commandes soit fermée. Ce n'est pas compliqué, mais il faut prendre le temps de bien tester pour vérifier qu'on n'introduit pas de comportement indésirable."

**Comment by theaverageguy** [comment]
I am working on this @martinec .

**Comment by eric-laporte** [comment]
This bug was solved by rahariti on 201 March 3
 [fix #7] Resolve The 'Explore graph paths' dialog box issue to display the results even if the Log dialog box is still open
