### ISSUE TITLE
Resizing the window that displays the text automaton

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/gramlab-ide#9]
The window displaying the text automaton (user manual, Section 7.1) can be resized with the mouse by dragging edges or corners, including the bottom edge. However, if the zone for the Elag output is minimized (as is the case on Figure 7.1, when you open the window), only the lower half of the bottom edge can be used to resize the window. The upper half of the bottom edge works differently. This difference is unexpected, since the edge is so thin.

**What is the expected output?**

By clicking and dragging the edge of the window, the user expects to resize the window. Especially if the double arrow appears when they hover the mouse over the edge.

**What do you see instead?**

If the zone for the Elag output is minimized (as when you open the window), and if you hover the mouse over the upper half of the bottom edge, the double arrow appears, but then if you click, you can't resize the window.
- if you grab and drag the edge up, the zone for Elag output appears (this is not likely to be what the user wanted; and there is another way to have this zone appear: the disclosure widget on the left of the bottom edge).
- if you try to grab and drag the edge down, nothing happens.

**More info**

The zone for the Elag output is what appears at the bottom of Figure 7.13 of the user manual.
The left-bottom and right-bottom corners work as expected.
I experienced the problem on Windows (now Windows 10).

**Comment by nikhilgupta23** [comment]
For resolving this, an EmptyBorder can be used for the JPanel. A border width of around 5 pixels will fulfill the purpose. The border can be placed around the entire frame or just at the bottom. I've attached images showing both. @martinec @eric-laporte Can you please go through the attachments and tell me whether this can be used to overcome the specified problem? Also, which of the two looks better?
![5allsides](https://cloud.githubusercontent.com/assets/11753315/14382813/3a125ef8-fdae-11e5-884e-e358d96d6e7f.JPG)
![5bottom](https://cloud.githubusercontent.com/assets/11753315/14382812/3a112fc4-fdae-11e5-885f-0512acc7ab30.JPG)

**Comment by martinec** [comment]
I guess a bottom border, as in the second screenshot, would be enough. But let @eric-laporte tell us more.

**Comment by eric-laporte** [comment]
A bottom border is OK, as in the second screenshot. Thanks!
