### ISSUE TITLE
Add LeXimir to the Unitex/GramLab IDE

### ISSUE THREAD

**Issue by rojorabelisoa** [UnitexGramLab/gramlab-ide#90]
**LeXimir is a module of dictionary management**

This dictionary management module enables concurrent manipulation of a set of dictionaries of lemmas, simple words or compounds, distributed in several files. This module enables the user to modify or delete all the information attached to a lemma, or the lemma itself, as well as to add new entries.

An important feature of this module is the ability of retrieving efficiently a subset of lemmas by
matching the lemmas, their part of speech (PoS), inflectional class code, syntactic and semantic
markers or their comments. For instance, one can look for all the dictionary entries starting
or ending with a search string.

**Comment by martinec** [comment]
Merged on master with 2dd0a67
