### ISSUE TITLE
error while compiling gramlab in eclipse

### ISSUE THREAD

**Issue by ghizlanelarfa** [UnitexGramLab/gramlab-ide#93]
When I  run the project in eclipse and Intellij I get the following bug when I try to preprocess text file. Any help please? 
Thanks.
![err](https://user-images.githubusercontent.com/32766048/35337879-9907193a-011c-11e8-91ec-53353f48c191.PNG)

**Comment by martinec** [comment]
I'm closing this issue for now. Feel free to reopen it by creating a new issue if the problem persists.
