### ISSUE TITLE
Inaccessible frame when using 'explore graph paths' tool

### ISSUE THREAD

**Issue by Kalkhas** [UnitexGramLab/gramlab-ide#98]
The error frame can't be accessed when there is an error using the _explore graph paths_ tool.

**What steps will reproduce the problem?**

  1. Open a graph which is found to be recursive (_Dnum.grf_ in [dnum_graph.zip](https://github.com/UnitexGramLab/gramlab-ide/files/1893913/dnum_graph.zip))
  2. Run the _Explore Graph Paths_ tool (with default options) on the graph

**What is the expected output?**

The error frame called _Done_ should be accessible to be closed before running the tool with different options for exemple.

**What do you see instead?**

![explore-graph-issue](https://user-images.githubusercontent.com/12595039/38546626-69220884-3cad-11e8-86a3-a41117ba6415.png)

The error frame can't be accessed as long as the _explore graph paths_ window is opened.

**More info**

This behaviour is caused by the way each frame is implemented in Gramlab. _Explore Graph Paths_ (__GraphPathDialog.java__) is a ***JDialog*** whereas the _error frame_ (__ProcessInfoFrame.java__) is a ***JInternalFrame***. A ***JDialog*** always has higher priority than a ***JInternalFrame***.

This behaviour has been mentioned in [issue #7] but wasn't addressed.

- Unitex/GramLab IDE version: 3.2.59-alpha
- UnitexToolLogger version: 3.2.59-alpha

**Comment by Kalkhas** [comment]
I found a related issue :
When an error occurs, if we close the 'explore graph paths' windows then reopen the tool to run a second exploration, the previous output remains in the new window.

I've corrected it in the same branch as this issue, should I create a new issue though ?

**Comment by martinec** [comment]
Hi @Kalkhas, there is not need to create a new issue but you might need to create a pull request with both fixes.
